export const seedData = {
  users: {
    _model: "User",
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      userLat: 39.9527237,
      userLong: -75.1635262,
      country: "United States",
      street: "Campus",
      addressCode: "T12Yne",
      DOB: "1976-02-13",
      phoneNumber: 1222222222,
      email: "homer@simpson.com",
      password: "Yoestoy",
    },
    margie: {
      firstName: "Margie",
      lastName: "Simpson",
      userLat: 36.7213028,
      userLong: -4.4216366,
      country: "Spain",
      street: "2 La calle Iglesia",
      addressCode: "B12YNOK",
      DOB: "1980-02-13",
      phoneNumber: 1995627281,
      email: "margie@simpson.com",
      password: "Yoestoy",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      userLat: 40.7127281,
      userLong: -74.0060152,
      country: "United States",
      street: "3 Wonderful Days",
      addressCode: "LO78UO",
      DOB: "1992-02-13",
      phoneNumber: 125622222,
      email: "bart@simpson.com",
      password: "Yoestoy",
    },
  },
  categories: {
    _model: "Category",
    park: {
      title: "Parks",
      userLat: -10.7127281567747,
      userLong: 74.006015225516,
      notes: "This category is used to note down all parks I would like to visit",
      userid: "->users.bart",
    },
    beach: {
      title: "Beaches",
      userLat: -3.712728164735647,
      userLong: 14.00601527465352,
      notes: "This category is used to note down all beaches I would like to go to",
      userid: "->users.homer",
    },
    museum: {
      title: "Museums",
      userLat: 36.7213028,
      userLong: -4.4216366,
      notes: "This category is used to note down all museums I would like to visit",
      userid: "->users.margie",
    },
  },
  placemarks: {
    _model: "Placemark",
    placemark_1: {
      title: "El Parque del Buen Retiro",
      lat: 40.41541290283203,
      long: -3.684231996536255,
      address: "Plaza de la Independencia, 728001",
      country: "Spain",
      phone: 89672435,
      website: "https://bit.ly/3bGwJUl",
      visited: "Yes",
      description:
        "Covering over 125 hectares and comprising more than 15,000 trees, El Retiro Park–recently named a UNESCO World Heritage Site–is a green oasis in the heart of the city. And more!!!",
      categoryid: "->categories.park",
    },
    placemark_2: {
      title: "Santa Monica beach",
      lat: 35.00535425523,
      long: -10.226577489,
      address: "Main Campus Marsille",
      country: "United States",
      phone: 1256789569,
      website: "https://www.loveholidays.ie/sem/santa-monica.html",
      visited: "No",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      categoryid: "->categories.beach",
    },
    placemark_3: {
      title: "National Gallery of London",
      lat: 51.508881,
      long: -0.1283826,
      address: "Trafalgar Square, London, WC2N 5DN",
      country: "United Kingdom",
      phone: 442077472885,
      website: "https://www.nationalgallery.org.uk/",
      visited: "Yes",
      description:
        "We are home to the national collection of paintings in the Western European tradition from the 13th to the 19th centuries. Our paintings are on show 361 days a year, free of charge.",
      categoryid: "->categories.museum",
    },
  },
};
